export const DETAIL_POST_REQUEST = "DETAIL_POST_REQUEST";
export const DETAIL_POST_SUCCESS = "DETAIL_POST_SUCCESS";
export const DETAIL_POST_FAIL = "DETAIL_POST_FAIL";

export const DETAIL_GET_REQUEST = "DETAIL_GET_REQUEST";
export const DETAIL_GET_SUCCESS = "DETAIL_GET_SUCCESS";
export const DETAIL_GET_FAIL = "DETAIL_GET_FAIL";

export const DETAIL_GET_APPLY_REQUEST = "DETAIL_GET_APPLY_REQUEST";
export const DETAIL_GET_APPLY_SUCCESS = "DETAIL_GET_APPLY_SUCCESS";
export const DETAIL_GET_APPLY_FAIL = "DETAIL_GET_APPLY_FAIL";

export const DETAIL_DELETE_REQUEST = "DETAIL_DELETE_REQUEST";
export const DETAIL_DELETE_SUCCESS = "DETAIL_DELETE_SUCCESS";
export const DETAIL_DELETE_FAIL = "DETAIL_DELETE_FAIL";

export const DETAIL_APPLY_USER_REQUEST = "DETAIL_APPLY_USER_REQUEST";
export const DETAIL_APPLY_USER_SUCCESS = "DETAIL_APPLY_USER_SUCCESS";
export const DETAIL_APPLY_USER_FAIL = "DETAIL_APPLY_USER_FAIL";
