export const JOB_POST_REQUEST = "JOB_POST_REQUEST";
export const JOB_POST_SUCCESS = "JOB_POST_SUCCESS";
export const JOB_POST_FAIL = "JOB_POST_FAIL";

export const JOB_GET_REQUEST = "JOB_GET_REQUEST";
export const JOB_GET_SUCCESS = "JOB_GET_SUCCESS";
export const JOB_GET_FAIL = "JOB_GET_FAIL";

export const JOB_GET_OWNER_REQUEST = "JOB_GET_OWNER_REQUEST";
export const JOB_GET_OWNER_SUCCESS = "JOB_GET_OWNER_SUCCESS";
export const JOB_GET_OWNER_FAIL = "JOB_GET_OWNER_FAIL";

export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAIL = "JOB_DELETE_FAIL";

export const JOB_UPDATE_REQUEST = "JOB_UPDATE_REQUEST";
export const JOB_UPDATE_SUCCESS = "JOB_UPDATE_SUCCESS";
export const JOB_UPDATE_FAIL = "JOB_UPDATE_FAIL";

export const JOB_GET_Page_REQUEST = "JOB_GET_Page_REQUEST";
export const JOB_GET_Page_SUCCESS = "JOB_GET_Page_SUCCESS";
export const JOB_GET_Page_FAIL = "JOB_GET_Page_FAIL";
