export const PROFILE_POST_REQUEST = 'PROFILE_POST_REQUEST'
export const PROFILE_POST_SUCCESS = 'PROFILE_POST_SUCCESS'
export const PROFILE_POST_FAIL = 'PROFILE_POST_FAIL'

export const PROFILE_GET_REQUEST = 'PROFILE_GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS'
export const PROFILE_GET_FAIL = 'PROFILE_GET_FAIL'

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'

export const PROFILE_GET_ALL_REQUEST = 'PROFILE_GET_ALL_REQUEST'
export const PROFILE_GET_ALL_SUCCESS = 'PROFILE_GET_ALL_SUCCESS'
export const PROFILE_GET_ALL_FAIL = 'PROFILE_GET_ALL_FAIL'